name: clean_architecture
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  lint: ^1.1.1
  cupertino_icons: ^0.1.2
  get_it: ^3.1.0
  flutter_bloc: ^3.1.0
  equatable: ^1.0.2
  dartz: ^0.8.9
  http: ^0.12.0+4
  shared_preferences: ^0.5.6
  data_connection_checker: ^0.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
